
url: http://r.extradecimal.com
baseurl: ""


#Name of website
title: " "


# Short description of your site
description: " "

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  Blog: "index"
  About:
    - Me: "aboutme"


# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/avatar-icon.png"

# adds a background pattern / image in the header and footer section
bgpattern: "/img/noisy_@2X.png"

author:
  name: Tvoj Otec
  email: "tvojotec@domain.com"
  github: tvojotecexample    # eg. daattali


# Select which links to show in the footer
footer-links-active:
  email: true
  github: true


# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Bratislava"
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
#permalink: /:year-:month-:day-:title/
paginate: 10
paginate_path: "/blog/page:num/"

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

gems:
  - jekyll-paginate

